// Copyright (c) 2019-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
// This file was generated by generate_device_frontend.py from Specializations.h

#pragma once
#include "VisGLDevice.h"

#include "VisGLDeviceObject.h"
#include "VisGLArrayObjects.h"
#include "VisGLInstanceObject.h"
#include "VisGLGroupObject.h"
#include "VisGLWorldObject.h"
#include "VisGLSurfaceObject.h"
#include "VisGLFrameObject.h"
#include "VisGLGeometryTriangleObject.h"
#include "VisGLGeometrySphereObject.h"
#include "VisGLGeometryCylinderObject.h"
#include "VisGLCameraPerspectiveObject.h"
#include "VisGLCameraOrthographicObject.h"
#include "VisGLMaterialMatteObject.h"
#include "VisGLMaterialTransparentMatteObject.h"
#include "VisGLMaterialPbrObject.h"
#include "VisGLLightDirectionalObject.h"
#include "VisGLLightPointObject.h"
#include "VisGLSamplerImage1DObject.h"
#include "VisGLSamplerImage2DObject.h"
#include "VisGLSamplerImage3DObject.h"
#include "VisGLSamplerTransformObject.h"
#include "VisGLSamplerPrimitiveObject.h"
#include "VisGLSpatial_FieldStructuredRegularObject.h"
#include "VisGLVolumeScivisObject.h"
#include "VisGLRendererDefaultObject.h"
