name: Build VisRTX
on:
  push:
    branches: [ next_release ]
  pull_request:
    branches: [ main, next_release ]
    paths:
      - 'devices/**'  # Only trigger if VisRTX device has changes
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [linux, windows]
        cudaversion: ['12.4.1', '13.0.2']
        config: [release, debug]
        include:
          - runs-on: ubuntu-22.04
            os: linux
            generator: Ninja
          - runs-on: windows-2022
            os: windows
            generator: Visual Studio 17 2022
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup CUDA Toolkit with Caching
        uses: ./.github/actions/setup-cuda
        with:
          cuda-version: ${{ matrix.cudaversion }}
          cache-key-suffix: ${{ hashFiles('.github/workflows/build-visrtx.yml') }}
      - name: Configure dependencies
        run: >
          cmake -LA -G "${{ matrix.generator }}" -B ${{github.workspace}}/deps_build
          -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/deps
          ${{github.workspace}}/devices/rtx/cmake/build_deps
      - name: Install dependencies
        run: >
          cmake --build ${{ github.workspace }}/deps_build --config ${{ matrix.config }}
      - name: Configure VisRTX
        run: >
          cmake -LA -G "${{ matrix.generator }}" -B ${{github.workspace}}/build-visrtx
          -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install
          -DCMAKE_PREFIX_PATH=${{ github.workspace }}/deps
          -DVISRTX_BUILD_RTX_DEVICE=ON
          -DVISRTX_PRECOMPILE_SHADERS=OFF
          -DVISRTX_BUILD_GL_DEVICE=OFF
          -DVISRTX_BUILD_TSD=OFF
      - name: Install VisRTX
        run: >
          cmake --build ${{ github.workspace }}/build-visrtx --config ${{ matrix.config }} --target install --parallel
